version: "2.2"

services:
  ############################
  # PHP + Apache
  ############################
  app:
    build:
      context: "."
      args:
        uid: ${UID}
    container_name: ${APP_NAME}_app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    restart: unless-stopped
    volumes:
      - ./:/var/www/html:cached
    ports:
      - 801:80
      - 4431:443

  ############################
  # MYSQL database
  ############################
  db_mysql:
    image: mysql:8.0.22
    container_name: ${APP_NAME}_mysql
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  ############################
  # MYSQL Testing database
  ############################
  db_test_mysql:
    image: mysql:8.0.22
    tmpfs: /var/lib/mysql
    container_name: ${APP_NAME}_mysql_test
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  ############################
  # PHPMyadmin service
  ############################
  phpmyadmin:
    container_name: ${APP_NAME}_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db_mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db_mysql
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 881:80
