version: "3.8"

services:
  ############################
  # PHP + Apache
  ############################
  app:
    build:
      context: "."
      args:
        uid: ${UID}
    container_name: ${APP_NAME}_app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - ./:/var/www/html:cached
    ports:
      - ${HTTP_PORT}:80
      #- 4431:443

  ############################
  # MYSQL database
  ############################
  db_mysql:
    image: mysql:8.0.22
    container_name: ${APP_NAME}_mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /var/lib/mysql

  ############################
  # PHPMyadmin service
  ############################
  phpmyadmin:
    container_name: ${APP_NAME}_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db_mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db_mysql
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - ${PHPMYADMIN_PORT}:80
  
  ############################
  # queue
  ############################
  worker_default:
    build:
      context: "."
      args:
        uid: ${UID}
    container_name: ${APP_NAME}_worker
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    restart: always
    command: "/usr/local/bin/php /var/www/html/artisan queue:work --queue=default"
  worker_low:
    build:
      context: "."
      args:
        uid: ${UID}
    container_name: ${APP_NAME}_worker_low
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    restart: always
    command: "/usr/local/bin/php /var/www/html/artisan queue:work --queue=low"
    
